In [29]:
import pandas as pd

In [30]:
data = pd.read_csv('CDC_CLEANED.csv')

FileNotFoundError: [Errno 2] File b'CDC_CLEANED.csv' does not exist: b'CDC_CLEANED.csv'

In [31]:
data.head()

,census_tract,conforming_loan_limit,derived_loan_product_type,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,...,total_units,income,debt_to_income_ratio,applicant_age,denial_reason-1,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_median_age_of_housing_units
0,3.711901e+10,C,Conventional:First Lien,Hispanic or Latino,Race Not Available,Joint,2,0,2,1,...,1,51.0,20%-<30%,55-64,10,7063,68.84,70700,84,15
1,3.711901e+10,C,Conventional:First Lien,Hispanic or Latino,Race Not Available,Joint,2,0,2,1,...,1,51.0,20%-<30%,55-64,10,7063,68.84,70700,84,15
2,3.708507e+10,C,Conventional:First Lien,Hispanic or Latino,Race Not Available,Male,3,0,2,1,...,1,36.0,20%-<30%,55-64,7,4746,46.46,56500,73,44
3,3.706502e+10,C,Conventional:First Lien,Not Hispanic or Latino,White,Male,4,0,2,1,...,1,39.0,NaN,25-34,10,3162,47.53,54700,79,38
4,3.718595e+10,C,Conventional:First Lien,Not Hispanic or Latino,White,Joint,1,8,2,1,...,1,92.0,38,45-54,10,4162,69.46,51600,74,40

In [32]:
data.dropna(inplace = True, thresh = 250000, axis = 1)

In [21]:
data.shape

(594769, 43)

In [22]:
data.columns

Index(['county_code', 'census_tract', 'conforming_loan_limit',
       'derived_loan_product_type', 'derived_ethnicity', 'derived_race',
       'derived_sex', 'action_taken', 'purchaser_type', 'preapproval',
       'loan_type', 'loan_purpose', 'open-end_line_of_credit',
       'business_or_commercial_purpose', 'loan_amount', 'loan_to_value_ratio',
       'interest_rate', 'rate_spread', 'total_loan_costs',
       'origination_charges', 'loan_term', 'interest_only_payment',
       'property_value', 'occupancy_type', 'total_units', 'income',
       'debt_to_income_ratio', 'co-applicant_credit_score_type',
       'applicant_ethnicity-1', 'co-applicant_ethnicity-1', 'applicant_race-1',
       'co-applicant_race-1', 'applicant_age', 'co-applicant_age',
       'applicant_age_above_62', 'denial_reason-1', 'tract_population',
       'tract_minority_population_percent',
       'ffiec_msa_md_median_family_income', 'tract_to_msa_income_percentage',
       'tract_owner_occupied_units', 'tract_one_to_four_family_homes',
       'tract_median_age_of_housing_units'],
      dtype='object')

In [23]:
data.drop(['open-end_line_of_credit', 'rate_spread', 'total_loan_costs', 'origination_charges',
        'loan_term', 'interest_only_payment',
       'co-applicant_credit_score_type',
       'applicant_ethnicity-1', 'co-applicant_ethnicity-1', 'applicant_race-1',
       'co-applicant_race-1', 'co-applicant_age','applicant_age_above_62'], inplace = True, axis =1)

In [24]:
data.head()

,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,...,debt_to_income_ratio,applicant_age,denial_reason-1,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,37119.0,3.711901e+10,C,Conventional:First Lien,Hispanic or Latino,Race Not Available,Joint,2,0,2,...,20%-<30%,55-64,10,7063,68.84,70700,84,2053,2733,15
1,37119.0,3.711901e+10,C,Conventional:First Lien,Hispanic or Latino,Race Not Available,Joint,2,0,2,...,20%-<30%,55-64,10,7063,68.84,70700,84,2053,2733,15
2,37085.0,3.708507e+10,C,Conventional:First Lien,Hispanic or Latino,Race Not Available,Male,3,0,2,...,20%-<30%,55-64,7,4746,46.46,56500,73,1068,1969,44
3,37065.0,3.706502e+10,C,Conventional:First Lien,Not Hispanic or Latino,White,Male,4,0,2,...,NaN,25-34,10,3162,47.53,54700,79,761,1416,38
4,37185.0,3.718595e+10,C,Conventional:First Lien,Not Hispanic or Latino,White,Joint,1,8,2,...,38,45-54,10,4162,69.46,51600,74,920,1872,40

In [25]:
import seaborn as sns
import matplotlib.pyplot as plt

In [26]:
data.dtypes

county_code                          float64
census_tract                         float64
conforming_loan_limit                 object
derived_loan_product_type             object
derived_ethnicity                     object
derived_race                          object
derived_sex                           object
action_taken                           int64
purchaser_type                         int64
preapproval                            int64
loan_type                              int64
loan_purpose                           int64
business_or_commercial_purpose         int64
loan_amount                          float64
loan_to_value_ratio                   object
interest_rate                         object
property_value                        object
occupancy_type                         int64
total_units                            int64
income                               float64
debt_to_income_ratio                  object
applicant_age                         object
denial_reason-1                        int64
tract_population                       int64
tract_minority_population_percent    float64
ffiec_msa_md_median_family_income      int64
tract_to_msa_income_percentage         int64
tract_owner_occupied_units             int64
tract_one_to_four_family_homes         int64
tract_median_age_of_housing_units      int64
dtype: object

In [27]:
data.drop(['tract_owner_occupied_units', 'tract_one_to_four_family_homes', 'county_code']
          , axis =1, inplace = True)

In [28]:
data.head()

,census_tract,conforming_loan_limit,derived_loan_product_type,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,...,total_units,income,debt_to_income_ratio,applicant_age,denial_reason-1,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_median_age_of_housing_units
0,3.711901e+10,C,Conventional:First Lien,Hispanic or Latino,Race Not Available,Joint,2,0,2,1,...,1,51.0,20%-<30%,55-64,10,7063,68.84,70700,84,15
1,3.711901e+10,C,Conventional:First Lien,Hispanic or Latino,Race Not Available,Joint,2,0,2,1,...,1,51.0,20%-<30%,55-64,10,7063,68.84,70700,84,15
2,3.708507e+10,C,Conventional:First Lien,Hispanic or Latino,Race Not Available,Male,3,0,2,1,...,1,36.0,20%-<30%,55-64,7,4746,46.46,56500,73,44
3,3.706502e+10,C,Conventional:First Lien,Not Hispanic or Latino,White,Male,4,0,2,1,...,1,39.0,NaN,25-34,10,3162,47.53,54700,79,38
4,3.718595e+10,C,Conventional:First Lien,Not Hispanic or Latino,White,Joint,1,8,2,1,...,1,92.0,38,45-54,10,4162,69.46,51600,74,40